apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qrcs-crm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://dev.azure.com/qrcs/_git/platform-manifests
    targetRevision: main
    path: apps/crm
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
